app = "smart-ui-ux-detector" # replace with your real app name

[env]
PORT = "8080"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1